image: ubuntu

stages:
  - build

.build_job: &build_def
  script:
    - ctest -VV -S cmake/TestVecCore.cmake

gcc:
  stage: build
  <<: *build_def
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y pkg-config python libgd-dev
    - apt-get install -y cmake git g++
  variables:
    CC: gcc
    CXX: g++

clang:
  stage: build
  <<: *build_def
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y pkg-config python libgd-dev
    - apt-get install -y cmake git clang
  variables:
    CC: clang
    CXX: clang++
